name: WorldModify
main: worldmodify.WorldModify
version: 1.2
commands:
   .limit:
      usage: /<command> <amount>
   .pos1:
      usage: /<command>
   .pos2:
      usage: /<command>
   .replace:
      usage: /<command> <block> <block>
   .set:
      usage: /<command> <block>
   .undo:
      usage: /<command>
   .replacenear:
      usage: /<command> <distance> <block> <block>
   .stack:
      usage: /<command> <amount>
   .copy:
      usage: /<command>
   .paste:
      usage: /<command>
   .distr:
      usage: /<command>